### ISSUE TITLE
Doesn't work on dynamically added elements

### ISSUE THREAD

**Issue by Szeliga** [souporserious/react-tether#1]
Hello,

First of all, thanks for this library, it's pretty sweet :)

I came across a bug when using `TetherElement` on dynamically added content. Here is a sample app I've came up with to demonstrate this - https://github.com/Szeliga/tether-react-bug-test-app

The path is like this:
* click add button
* a new element appears (1) with no tethered content visible (an empty div is added to body)
* click add buton again
* another element appears (2) with no tethered content and for element 1, the tethered content appears
* and so on

I would like to fix this and submit a PR, but my React knowledge is very slim and I have no idea where to luck for this bug. If you don't have time for fixing this yourself, could you point me in the right direction at least? :)

Best regards,
Szymon

**Comment by souporserious** [comment]
Dang, I knew this would be a problem in certain use cases. If you need to show the content before the target component is rendered you will need to add a forceUpdate inside the target component's componentDidMount lifecycle method. So you would have to split that up to have it's own component so you could forceUpdate it. Unfortunately, I'm not sure the way around this. It has to do with the element not being available in the DOM yet so Tether won't instantiate until the node is available. If there is another way this can be fixed I am open to suggestions. I might be able to expose something like a `TetherTarget` component and they can synced in some way.

**Comment by Szeliga** [comment]
Great, thanks for the tip! :) I will check it out today. I will revisit this issue once my react knowledge is more in-depth, maybe I'll have some idea how to fix this.

**Comment by souporserious** [comment]
Awesome, sounds good! Thanks for reporting your findings :) hopefully we can figure out a better way to handle this so `forceUpdate` is not needed.

**Comment by souporserious** [comment]
@Szeliga just rewrote the API for this, do you mind trying it out and letting me know if it solves your problem?

**Comment by souporserious** [comment]
@Szeliga going to close this, it seems to be working fine on my end now. Please let me know if there are any issues for you and I will investigate further.

**Comment by Szeliga** [comment]
Yep, everything works fine now, thanks!
