### ISSUE TITLE
Cut a release (0.3.2?)

### ISSUE THREAD

**Issue by rafeememon** [souporserious/react-tether#11]
There are a couple fixes that we'd like to include in react-datepicker, specifically #5, #7 and #9.  Please make a new release so we can consume them.

Thanks!

**Comment by souporserious** [comment]
https://github.com/souporserious/react-tether/releases/tag/0.3.2 done :) thanks for the help!

**Comment by rafeememon** [comment]
Great, thank you!  Looking forward to using this =)
