### ISSUE TITLE
renderElementTo not working when specified element is not directly under body

### ISSUE THREAD

**Issue by essekia** [souporserious/react-tether#14]
I find that if the render-to-element is a direct child of 'body', it works or else it defaults to the body itself.

```
     // console.log("tool-tip-container: " + jQuery('#tool-tip-container').length);
        var ElementToolTips = React.createElement(TetherComponent, {
            attachment: "top left",
            targetAttachment: 'top right',
            renderElementTo: document.getElementById('tool-tip-container'),
            key: fakeKey,
            className: fakeKey,
        }, rootAtom, toolTipContainer);
```

Anyone else has this issue?

**Comment by souporserious** [comment]
Fixed in the latest release. Now uses `document.querySelector`.

**Comment by slorber** [comment]
not sure but it seems to me renderElementTo never works because in my case it looks like tether put the element in the body while your lib inserted it in the correct place in the first place

**Comment by ConneXNL** [comment]
@slorber I have the same problem.

@souporserious  Why is renderElementTo even an option when tether doesn't support it?
https://github.com/HubSpot/tether/issues/189

**Comment by pzuraq** [comment]
Tether technically will allow you to render to another element, so long as that element is positioned statically compared to the body. It was a fix I put in some time ago to _try_ to make this kind of manipulation possible for us in single page app frameworks, unfortunately it doesn't really work as we need it to, thus my PR to Tether
