### ISSUE TITLE
Problem with `renderElementTo`

### ISSUE THREAD

**Issue by bekerov** [souporserious/react-tether#16]
Hello. Can you provide sample props for `renderElementTo`.
`this.refs.calendar`, `ReactDOM.findDOMNode(this.refs.calendar)` not affected to render element?
```
const renderTo = renderElementTo || document.body
renderTo.appendChild(this._elementParentNode)
```

I'm using component which use `react-tether`
https://github.com/Hacker0x01/react-datepicker/issues/434#issuecomment-207445673

Can you provide simple example whicj works ?

**Comment by souporserious** [comment]
Fixed in the latest release. Now uses `document.querySelector`.

**Comment by bekerov** [comment]
oh thanks
