### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by mking-clari** [souporserious/react-tether#18]
Just wanted to say this component made a huge difference for my app. I was having a lot of trouble hooking up top level dropdowns and tooltips in my Redux app (I was passing around a bunch of bounding rects to properly position panels). Using Tether has really cleaned this up by reducing the amount of global knowledge being passed around (target and element being colocated in the code, even if they aren't colocated in the DOM tree).

**Comment by souporserious** [comment]
You're very welcome :) glad it could help.
