### ISSUE TITLE
Element is positioned incorrectly when flipped horizontally and the body has a scrollbar

### ISSUE THREAD

**Issue by shw6rn** [souporserious/react-tether#24]
When the element needs to flip because it would go off the edge of the screen and the body has a scrollbar, it is positioned incorrectly (it is off by the width of the scrollbar)

![withscrollbar](https://cloud.githubusercontent.com/assets/5312404/16492727/c23a55a4-3eb0-11e6-8df3-840e66e95b07.JPG)

Use the following React component to reproduce:
```javascript
import React from 'react';
import TetherComponent from 'react-tether';

document.body.style['overflow-y'] = 'scroll';

const TetheredThing = React.createClass({
  getInitialState() {
    return {
      open: false
    };
  },
  onClick() {
    this.setState({open: !this.state.open});
  },
  render() {
    const buttonStyle = {
      position: 'absolute',
      right: '50px',
      height: '100px',
      width: '100px',
      backgroundColor: 'red'
    };

    return (
      <TetherComponent
        attachment="top left"
        targetAttachment="bottom right"
        constraints={[
          {
            to: 'window',
            attachment: 'together'
          }
        ]}>
        <button style={buttonStyle} onClick={this.onClick}>
          {'Click on me'}
        </button>
        {this.state.open ? <div style={{height: '100px', width: '100px', backgroundColor: 'green'}}></div> : undefined}
      </TetherComponent>
    );
  }
});

export default TetheredThing;
```

When you do not apply the scrollbar to the body, the element is positioned correctly.
![withoutscrollbar](https://cloud.githubusercontent.com/assets/5312404/16492801/0f9befc4-3eb1-11e6-9ba3-0c6cea8932c5.JPG)

Additionally, this problem only happens the first time the element renders. I've modified the component above to demonstrate:
```javascript
import React from 'react';
import TetherComponent from 'react-tether';

document.body.style['overflow-y'] = 'scroll';

const TetheredThing = React.createClass({
  onClick() {
    this.forceUpdate();
  },
  render() {
    const buttonStyle = {
      position: 'absolute',
      right: '50px',
      height: '100px',
      width: '100px',
      backgroundColor: 'red'
    };

    return (
      <TetherComponent
        attachment="top left"
        targetAttachment="bottom right"
        constraints={[
          {
            to: 'window',
            attachment: 'together'
          }
        ]}>
        <button style={buttonStyle} onClick={this.onClick}>
          {'Click to force update'}
        </button>
        <div style={{height: '100px', width: '100px', backgroundColor: 'green'}}></div>
      </TetherComponent>
    );
  }
});

export default TetheredThing;
```

**Comment by souporserious** [comment]
I've been experiencing similar issues. Trying to figure out how I can handle it the best way. I was thinking I could detect when the second child has been mounted and fire the `position` method on the TetherComponent. I'm open to any ideas though.

**Comment by shw6rn** [comment]
That seems like a reasonable approach. The issue seems to be trying to position the element when it isn't fully on the DOM. Not absolutely sure about that though.

**Comment by souporserious** [comment]
@shw6rn I'm unable to reproduce locally. Can you please create a [Codepen](codepen.io) and try to reproduce?

**Comment by shw6rn** [comment]
I've created a codepen here: http://codepen.io/shw6rn/pen/yJbVkz

**Comment by souporserious** [comment]
Thank you very much. Unfortunately, I still can't reproduce it on my machine :/ what OS and browser are you using?

**Comment by shw6rn** [comment]
I am on Windows 7 - I see the bug on Chrome, Firefox, and IE11

**Comment by souporserious** [comment]
Awesome, thank you! I see it now. I'm looking into it.

**Comment by souporserious** [comment]
@shw6rn I can't seem to figure out how to solve this without your forceUpdate. Here is my take on trying to fix it http://codepen.io/souporserious/pen/BzRWkq?editors=0010 but still no dice. If you can find a fix or maybe a better way to handle running tether through React I'm open to ideas/PR's.

**Comment by shw6rn** [comment]
@souporserious After further investigation, I discovered that this was a problem with Tether. I've opened a [pull request with Tether](https://github.com/HubSpot/tether/pull/190/files) and I'll close this issue! Thanks for looking into it.
