### ISSUE TITLE
Support hot reloading

### ISSUE THREAD

**Issue by slorber** [souporserious/react-tether#27]
Hi,

It would be nice if the component could support hot reloading: I change tether offset in my code and after hot reloading I'd like the tooltip/dropdown/hotspot adjusted on the screen.

Ie on hot reload the component could do something:

```
this._tether.setOptions(tetherOptions)
this._tether.position()
```

Not sure how this could be done but this may work

**Comment by souporserious** [comment]
Currently it does that: https://github.com/souporserious/react-tether/blob/master/src/TetherComponent.jsx#L167-L173

Unfortunately, I have no clue how to get this to work with hot reloading :/ I'm open to a PR if you find a good solution.

**Comment by slorber** [comment]
hmmm actually I think it may work it's just my code that prevents hot reloading

**Comment by slorber** [comment]
Actually it works
