### ISSUE TITLE
Integration with tether event system

### ISSUE THREAD

**Issue by slorber** [souporserious/react-tether#28]
Hi,

Tether has an event system that permits to attach listeners to events. It is however not documented.

It would be useful for me if we could implement this in react-tether. The tether object expose some methods through inheriting an [Evented](https://github.com/HubSpot/tether/blob/5f90608d5aeb098ae28b6b3de8b0c011bdf479f1/src/js/utils.js#L291) class.

I've hacked a bit the lib and it works fine if we register listeners on mount, like:

```javascript
<TetherComponent
        attachment={this.props.hotspotPosition}
        targetAttachment={this.props.hotspotPosition}
        className={"onboarding-hotspot-tethered " + this.props.name}
        offset={this.props.hotspotOffset}
        constraints={[{
          to: 'scrollParent',
          attachment: 'none'
        }]}
        on={[
          {
            event: "repositioned",
            fn: this.repositionTooltip
          }
        ]}
      >
```

I simply added this on componentDidMount:

```javascript
      (this.props.on || []).forEach(function(onItem) {
        this._tether.on(onItem.event,onItem.fn,onItem.ctx);
      }.bind(this));
```

Also would be interested to update tether to 1.3.4 that's going to be release soon and introduces a new "repositioned" event that I need. 

For context, see:
- https://github.com/HubSpot/tether/issues/195
- https://github.com/HubSpot/tether/pull/196

I'm interested to contribute to this repo as we actively use tether for a long time. This issue is mostly for discussions about the API that we'd like for this feature and I'll find time to make a PR.

I think the simplest is to allow the user to register listeners on mount like I did, but to also expose tether event methods through component imperative API

**Comment by souporserious** [comment]
Totally down for this. How do you feel about a prop named `events` that works the same way. I'm guessing the user has to take care of the `off`? Would it be weird to handle that part of it in `componentWillUnmount`?

I will update to the latest Tether once it is released.

**Comment by slorber** [comment]
I don't think it's weird I think it's already what happens when you call `tether.destroy()`

I'd expose that `events` prop for listening to events while the component is mounted + also an imperative api for on/off in case user would want to do more fancy things

**Comment by souporserious** [comment]
So maybe allowing props like `onRepositioned`, `onFooTetherEvent`, etc?

**Comment by slorber** [comment]
Makes sens as a shortcut, but the tether api also gives some extra options like listener binding context and possibility to listen to only first event. Not sure these are really useful for react however...

Seems for now there are only 2 events: `update` and the new `repositioned `. 
Maybe 2 optional func callbacks like you describe would be nice and simple. it solves my usecase.
