### ISSUE TITLE
Example project broken

### ISSUE THREAD

**Issue by alex-paterson** [souporserious/react-tether#34]
None of the elements are rendering properly. 
Also, can I confirm that the `renderElementTo` prop also no longer works, and we must instead give `TetherComponent` two children?
Thanks!

**Comment by souporserious** [comment]
The example project should be good now. You can see a live version [here](https://souporserious.github.io/react-tether/). `renderElementTo` is where you want the Tethered content to be placed in the DOM. It's documented more [here](https://github.com/souporserious/react-tether#renderelementto-proptypesstring).

**Comment by alex-paterson** [comment]
Thanks!

**Comment by scf4** [comment]
@souporserious 'toggle drop' doesn't seem to work for me, and I'm trouble implementing react-tether into my project. Does it work with React 16?
