### ISSUE TITLE
Using the `renderElementTo` prop

### ISSUE THREAD

**Issue by majapw** [souporserious/react-tether#35]
Hi there!

I'm using `react-tether` in `react-dates` and having some trouble trying to change the location the `tether-element` renders to. Basically, I'm trying to set up get the tethered version of the datepicker working inside of a portal or modal-like object.

My example set-up is as follows:
```
const button = <button type="button">Open Portal</button>
return (
  <Portal
    style={{ marginTop: '2px'}}
    openByClickOn={button}
    closeOnOutsideClick
  >
    <div
      className="tetherParent"
      style={{
        background: '#fff',
        padding: '24px',
        margin: 'auto',
      }}
    >
      This portal closes on outside click.
      <DateRangePickerWrapper
        tetherParentSelector=".tetherParent"
      />
    </div>
  </Portal>
);
```

And then the `TetherComponent` set-up is here:
```
<TetherComponent
  classPrefix="DateRangePicker__tether"
  renderElementTo={document.querySelector(tetherParentSelector)}
  attachment={`top ${anchorDirection}`}
  targetAttachment={`bottom ${anchorDirection}`}
  offset="-23px 0"
  constraints={[{
    to: 'scrollParent',
    attachment: 'none',
    pin: [tetherPinDirection],
  }]}
>
  ...
</TetherComponent>
```

I tried using refs initially, but because those don't exist at the time of render, that's not really possible. I even tried changing the `to` value of my constraint to `document.querySelector(tetherParentSelector)`, which kind of worked... but didn't actually change the DOM as expected and broke the portal somehow. Do you have any advice?

**Comment by souporserious** [comment]
Hmm weird. I'll have to look into it. Is it possible you can get me a reduced test case in a Codepen or something similar?

**Comment by majapw** [comment]
Let me try to throw something together!

**Comment by souporserious** [comment]
Thank you! I have limited time, so anything helps :)

**Comment by souporserious** [comment]
@majapw I think I know what the cause is now. It looks like `react-dates` uses `react-portal` as a dependency. This library uses its own portal. I think `react-dates` will need to allow more compose-ability to be play nice with `react-tether`.

**Comment by majapw** [comment]
I ended up pulling out the library for now (we were only using one small tether feature), but I think you may be right. It works really really well in some cases, but not all because of this lack of compose-ability. 

Thanks for `react-tether` anyways! I was trying to use tether out of the box and it was just not playing nicely with react so this is a really cool library. :)

**Comment by souporserious** [comment]
Yeah, hopefully that can change in the future. If you're interested in a compose-able calendar in React I've been working on [React Midnight](https://github.com/souporserious/react-midnight) when I can. We use it in production at my work. No docs yet, but you can check the examples folder to see how it works.
