### ISSUE TITLE
Release 0.5.4 is broken on npm

### ISSUE THREAD

**Issue by Nickman87** [souporserious/react-tether#37]
I'm getting Module not found errors in our build for the react-tether module.
Looking in the package.json, the main entry is located at lib/react-tether.js but the lib folder seems to be missing in the latest release on NPM
@souporserious

**Comment by kevart** [comment]
I've downgraded to 0.5.2 that worked for me.

**Comment by Nickman87** [comment]
Yeah, that's what I did as well

**Comment by souporserious** [comment]
Should be fixed in the latest release with this PR https://github.com/souporserious/react-tether/pull/39. Sorry about that 😁

**Comment by j0hnsmith** [comment]
This will require a new release to be pushed to npm, won't it?

**Comment by souporserious** [comment]
There was one https://github.com/souporserious/react-tether/commit/c6add9f42a53581d20c6cb2973a7027ad3b83d6c :)

**Comment by j0hnsmith** [comment]
Thanks, I see it now, couldn't at the time I wrote the comment.
