### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-tether' in [..]/node_modules/pui-react-overlay-trigger

### ISSUE THREAD

**Issue by kevart** [souporserious/react-tether#38]
Both modules are installed.

```
pui-react-overlay-trigger@6.0.2
react-tether@0.5.4
```

All other modules can be included (via _require_) without issue.

**Comment by GabrielCousin** [comment]
Experiencing this issue with react-tether as direct dependency.

**Comment by slorber** [comment]
yes I think @souporserious has published the new release in a bad way because the npm deployment does not include any lib/dist folder

In the meantime you can fix version to 0.5.2

**Comment by GabrielCousin** [comment]
Yep. Plus, somebody has already submitted a PR.

**Comment by souporserious** [comment]
Should be fixed in the latest release with this PR https://github.com/souporserious/react-tether/pull/39. Sorry about that 😁
