### ISSUE TITLE
Server-side rendering regression

### ISSUE THREAD

**Issue by rafeememon** [souporserious/react-tether#4]
We recently started using this library in the [react-datepicker](https://github.com/Hacker0x01/react-datepicker) package.  Version 0.3.0 introduced an eagerly-evaluated reference to `document.body` that causes server-side rendering to fail with a `ReferenceError: document is not defined`.  A repro is given on Hacker0x01/react-datepicker#352.

**Comment by rafeememon** [comment]
Thanks!

**Comment by souporserious** [comment]
No problem. Thanks for the PR :)

**Comment by rafeememon** [comment]
@souporserious, would you be able to cut a release that includes this fix?  Please let me know!
