### ISSUE TITLE
Reposition and update event props are not called.

### ISSUE THREAD

**Issue by aight8** [souporserious/react-tether#40]

**Comment by aight8** [comment]
Sometimes the following error is showed:
```
this._tether.on is not a function
```

**Comment by souporserious** [comment]
@slorber any idea here? Should we just check if `this._tether` exists?

**Comment by alexstrat** [comment]
I actually think that `_registerEventListeners` should be called just after a Tether instance is created, ie roughly here: [TetherComponent.jsx#L197](https://github.com/souporserious/react-tether/blob/master/src/TetherComponent.jsx#L197)

**Comment by slorber** [comment]
I agree with @alexstrat also had the case in my app where the tether component is hidden initially

Note that when using the imperative api you still need to make sure the tethered element is displayed otherwise you'll get the same error

**Comment by slorber** [comment]
Also note that if the fn provided as props get updated we probably should deregister/reregister on component update.

I only provided a basic initial implementation of event system but we can certainly go a lot further
