### ISSUE TITLE
Reposition the tether component

### ISSUE THREAD

**Issue by LucMerceron** [souporserious/react-tether#43]
Hello guys,

I would like to know if there is any plan to allow the re-positioning of the component when the target is moving (without a user action - imagine an animation) ?
I think one way to do it would be to be able to call [Tether position](http://tether.io/overview/repositioning/) function from my react-tether component.

Thanks,
Luc

**Comment by souporserious** [comment]
Hello, sorry for the late reply. You can use the `getTetherInstance` and use any regular Tether methods or call `position` and that will reposition the Tether.

Something like this:
```
<TetherComponent ref={component => component.position()}>
  ...
</TetherComponent>
```

Please let me know if you have any other questions :)

**Comment by LucMerceron** [comment]
Hello,
Thank you for the response.

I still have a problem, the console is printing me `undefined` when I'm trying to access `component.position()` and does nothing. It does not print a warning when I try to access directly the _tether object with `this.comp._tether.position()` but does not trigger a position rendering too.

Thank for your help,
Luc

**Comment by LucMerceron** [comment]
It is working thank you
