### ISSUE TITLE
Setting `attachment: "top right"` in IE 11 results in `left: 0px`

### ISSUE THREAD

**Issue by mvincent7891** [souporserious/react-tether#45]
When using the attachment prop and setting it to `top right` in Safari and Chrome, this results in the tethered component having css property, `right: 0px`. 

However, in IE 11, this results in `left: 0px`.

We're having to detect the user's browser and pass in `top left` in the case of IE 11 in order to get the correct functionality.

**Comment by souporserious** [comment]
Can you please confirm if this has to do with the React wrapper and not the core library?

**Comment by souporserious** [comment]
Closing this since I believe it has to with the core library. Please feel free to reopen.
