### ISSUE TITLE
Error on unmount if never opened

### ISSUE THREAD

**Issue by rafeememon** [souporserious/react-tether#8]
If the component is rendered into the DOM but never opened, the following error occurs because of calling `ReactDOM.unmountComponentAtNode` with a null node:

```
Uncaught Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.
```

**Comment by halloffame** [comment]
I'm getting the same error, I tracked it down to this line:

https://github.com/souporserious/react-tether/blob/7fbbaad359c2916eedf6f78a88d2160059a98d49/src/TetherComponent.jsx#L78

In my case `this._elementParentNode` is null when it is trying to unmount, which is why it is throwing the error.
